apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
    - port: 50000
      name: jenkins-master
  selector:
    name: jenkins-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-app
spec:
  template:
    metadata:
      labels:
        name: jenkins-app
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jenkins-app
          image: jenkins
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-vol
          awsElasticBlockStore:
            volumeID: vol-0c1871efabd4f651b
            fsType: ext4
